### ISSUE TITLE
Missing executables

### ISSUE THREAD

**Issue by duog** [domenkozar/hie-nix#25]
Hi,

I've been trying to get this to work with emacs on nixos. I've been adding `hies` to my build environment. I've run into problems where the executables `hie-wrapper` and `cabal-helper` are not available. 

I think the `hie-wrapper` executable from the hie84 should be provided by the `hies` derivation, but `cabal-helper` should be a run-time dependency of hie. Do you agree or am I hopelessly confused?

**Comment by sib-null** [comment]
I have this same problem on vscode.  `hie-wrapper` isn't installed and is not in the path, as a result [hie-vscode.sh](https://github.com/alanz/vscode-hie-server/blob/master/hie-vscode.sh) can't find the hie executable.

Thanks to @duog, at least I have a workaround by installing `hie84`. However, hie84 also doesn't install the `hie-wrapper` executable, but rather, `hie-vscode.sh` checks to see if the `hie` executable exists in path, and since we are installing a single version hie, it does exist.

**Comment by domenkozar** [comment]
I agree about `cabal-helper`, will add it there.

For `hie-wrapper` it's due to the fact that hie git revision is older than the wrapper itself, it needs an update.

**Comment by duog** [comment]
I can't reproduce this now. I'm not sure how I managed to get the error, as you say it doesn't make any sense.
